### ISSUE TITLE
No tooltip is displayed on sidebar videos

### ISSUE THREAD

**Issue by DerpMcDerp** [ParticleCore/Iridium#389]
The firefox browser disables tooltips for the title attribute if you have this:

```css
/* Iridium.css: */
a.yt-simple-endpoint span { pointer-events: none }
```

Which causes no tooltip to appear for `<span title="some long video title">` when you hover on any video thumbnail in the sidebar.
