### ISSUE TITLE
Add ability to remove home screen banner advertising

### ISSUE THREAD

**Issue by MattSturgeon** [ParticleCore/Iridium#81]
The advert header on the homesecreen has id `masterhead-ad` so can be easily hidden with the same method as #74:

```css
#masthead-ad {
    display: none !important;
}
```
