### ISSUE TITLE
Sheduled live stream shows black while waiting for video to start

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#966]
When opening a video that is scheduled to start in the future the player shows all in black. The reason for this is the styling meant to correct autoplay behavior is not accounting for this scenario.

The fix is simple as far as I could find, the following rule:

https://github.com/ParticleCore/Iridium/blob/43d756dedcc92b7a6163195c0ec09e0525207607/src/firefox/css/content-script.css#L2-L4

needs to be updated to

````css
#movie_player.unstarted-mode:is(.playing-mode, .paused-mode):not(.buffering-mode) > *:not(.ytp-cued-thumbnail-overlay) {
    display: none;
}
````

May need to revisit this in the future if some odd scenarios come up, but so far seems to be sufficient.
